console.log("Hello World")

//keyword variabel : var , let , const
 var angka ;

 angka = 20;
 console.log("20")
 angka = 30;
 console.log("30")

//=========(Var)

 var greeting=" Hello Welcome !"
 console.log("Hello Welcome !")
 var greeting="Rian Mulyana"
 console.log("MR.Rian Mulyana")

 //=========(let) 

 let x = 25;
 console.log(x);
 x = 45;
 console.log(x);
 let angka3 = '30'
 console.log(angka3)

  //===========(Const)

 const phi = 3.14
 console.log (phi)

 

 